### ISSUE TITLE
 builded error "  sub-hello-qmake_all"

### ISSUE THREAD

**Issue by carmanlwf** [VSRonin/QtXlsxWriter#11]
qtxlsx.pro builded by qt5.9 MINGW qtcreator (perl 5 ,version 24,subversion 0(v5.24.0)) in windows, but failed,
the error is "sub-hello-qmake_all"

**Comment by VSRonin** [comment]
Could you be more specific in the error, report the few lines above?
Did you try building with CMake?

**Comment by chiffonqian** [comment]
intalling perll will fix this

**Comment by carmanlwf** [comment]
问题是 不能直接编译整个项目（编译会提示 sub-hello-qmake_all"） ，只编译源码部分是没有问题的   谢谢
