### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by zuzuviewer** [VSRonin/QtXlsxWriter#12]
centos 7,Qt5.9.0.
succeed with qmake,but "make" failed,it show "g++:error:unrecognized command line option '-std=c++1z"

**Comment by VSRonin** [comment]
Can I ask what compiler are you using?

**Comment by zuzuviewer** [comment]
@VSRonin,GNU Make 3.82

**Comment by VSRonin** [comment]
Strange that it would require C++17 standard. it should not.
Can I ask how you are building the library?

**Comment by zuzuviewer** [comment]
@VSRonin ，I follow README document's "Usage(1): Use Xlsx as Qt5's addon module" steps

**Comment by zuzuviewer** [comment]
it was work with cmake 3.9.0

**Comment by VSRonin** [comment]
This is very strange, in theory the 2 methods should be equivalent.
Thanks for bearing with me on this, hope the CMake solution is good enough

**Comment by zuzuviewer** [comment]
Yes,the CMake solution is good
