### ISSUE TITLE
Edit an existing .xlsx file

### ISSUE THREAD

**Issue by Gaalee** [VSRonin/QtXlsxWriter#13]
Hello, pretty much the title, how can I edit an existing .xlsx file using QtXlsxWriter.

Sorry english is not my native langage so, if you want more explanation feel free to ask.

Thank you to update this usefull addon. Hope you can help me quickly because i need to finished my project in 2 weeks.

**Comment by VSRonin** [comment]
You can use [this example](http://qtxlsx.debao.me/qtxlsx-demo-main-cpp.html) as a base only instead of a new document you will use an existing one as in http://qtxlsx.debao.me/qtxlsx-extractdata-example.html

**Comment by Gaalee** [comment]
Hi, i managed to obtain what i want, thank you. By any chance, is there a way to convert a .xlsx to pdf with QtXlsxWriter ? If not, do you know how to do it ?

**Comment by VSRonin** [comment]
No and it's outside the scope of this library. Basically there is no "GUI" in this library and there is no information about how the file should be rendered.
The only way is manually build a table model or a text table using the information provided by the library and use Qt's PDF printer to save it to PDF
