### ISSUE TITLE
read bug

### ISSUE THREAD

**Issue by joplevy** [VSRonin/QtXlsxWriter#20]
im testing the library and the read function dont seems to work ... the cellAt() function give me NULL pointer to

**Comment by VSRonin** [comment]
The tests are passing on my side so I think it's a problem with your code.
Are you sure that cell you are reading has something in it?

**Comment by joplevy** [comment]
This was my mistake, I dont know why the library couldn't open the files, even a write overwrited the files. I dit the update of Qt from 5.9.3 to 5.10 and this solved my problem
