### ISSUE TITLE
Can write but not read

### ISSUE THREAD

**Issue by insofern** [VSRonin/QtXlsxWriter#32]
I want to read and write Xlsx-Files with Qt and use the QXlsx module: http://qtxlsx.debao.me/
While I can write into xlsx-files, read does not work
I copied this example into my code http://qtxlsx.debao.me/qtxlsx-extractdata-main-cpp.html

`{
//Create a new .xlsx file.
QXlsx::Document xlsx;
xlsx.write("A1", "Hello Qt!");
xlsx.write("A2", 12345);
xlsx.write("A3", "=44+33");
xlsx.write("A4", true);
xlsx.write("A5", "http://qt-project.org");
xlsx.write("A6", QDate(2013, 12, 27));
xlsx.write("A7", QTime(6, 30));
xlsx.saveAs("Book1.xlsx");
}

QXlsx::Document xlsx("Book1.xlsx");

qDebug()<<xlsx.read("A1");
qDebug()<<xlsx.read("A2");
qDebug()<<xlsx.read("A3");
qDebug()<<xlsx.read("A4");
qDebug()<<xlsx.read("A5");
qDebug()<<xlsx.read("A6");
qDebug()<<xlsx.read("A7");

for (int row=1; row<10; ++row) {
    if (QXlsx::Cell *cell=xlsx.cellAt(row, 1))
        qDebug()<<cell->value();
}`

and in my headerfile I added the line:

`#include "xlsx/xlsxdocument.h"

The output I get is:

`QVariant(Invalid)`

Can anyone help me?
Thanks

**Comment by VSRonin** [comment]
It's probably just a path issue. Try replacing "Book1.xlsx" with the full absolute path to the file

**Comment by insofern** [comment]
Thanks
https://stackoverflow.com/questions/42353619/qt-5-5-project-build-error-in-qt-5-8
This was the issue

**Comment by VSRonin** [comment]
That should not apply to this fork. That problem only affects the old unmaintained version
