### ISSUE TITLE
Question:Read a cell value when it has formulas

### ISSUE THREAD

**Issue by S5642** [VSRonin/QtXlsxWriter#36]
I write a formular in worksheet, but how can read the reality result when the cell has fomular? If the cell has formular, does it only can output formular string?

**Comment by VSRonin** [comment]
This library does not provide a calculation engine. It's beyond its scope. It will never asses the value of a cell once you wrote a formula in it.
You can either write it yourself as a separate piece of your software or rely on MS excel/Libre office calc to do the work for you.
