### ISSUE TITLE
VBA will lose after write a xlsm type file

### ISSUE THREAD

**Issue by liufeijin** [VSRonin/QtXlsxWriter#41]
XLSM type file contains VBA .
if write it the VBA will lose as below red mark

![XLSMFILE](https://user-images.githubusercontent.com/19425403/61988400-30434580-b053-11e9-9546-eac8957849e8.png)

the vbProject.bin is lost in xlsm zip file
cloud you fix it?
Many thanks

**Comment by VSRonin** [comment]
Every time this library writes a file, it will not edit the existing one but write it from scratch. So any feature present in the file before that are not supported by this library will be lost.
As VBA code is not supported it will indeed not be inserted in the result.
It is unlikely this will change in the future as the vba part of the file is still stored in the same way as pre-xlsx files and it's a proprietary binary format of Microsoft.
https://github.com/jmcnamara/libxlsxwriter offers a way to insert an existing vbaProject.bin inside a xlsx file

**Comment by liufeijin** [comment]
Hi VSRonin
Many thanks for your information . 
I have fixed it   refer your information on QXlsx project https://github.com/QtExcel/QXlsx
but i just completed the vba of thisworkbook. for each sheet VBA is not fixed still.
If have a free time , will try to fix  VBA of each sheet and printsetting bin file .
best regards,
jeff
