### ISSUE TITLE
Can this library run inVisual Studio with Qt

### ISSUE THREAD

**Issue by ouxs** [VSRonin/QtXlsxWriter#43]
I tried to import it into my vs project, but there was an error.
But in QT creator, it's normal.

**Comment by VSRonin** [comment]
It works in VS but your description is a bit too vague to diagnose the problem. You are probably missing some defines (`QT_BUILD_XLSX_LIB` is the main suspect), look at the project files for clues

**Comment by ouxs** [comment]
```
--- (Import): Generating new project of xlsx.pro file
--- (qmake) : Using: C:\QT\QT5.12.5\5.12.5\MSVC2017_64\bin\qmake
--- (qmake) : Working Directory: C:\Users\liqinglin\Desktop\xlsx
--- (qmake) : Arguments: -tp vc "xlsx.pro" -o "xlsx.vcxproj" QMAKE_INCDIR_QT=$(QTDIR)\include QMAKE_LIBDIR=$(QTDIR)\lib QMAKE_MOC=$(QTDIR)\bin\moc.exe QMAKE_QMAKE=$(QTDIR)\bin\qmake.exe

[1] - Project ERROR: Module does not define version.

--- (Import): Error(s): 1
--- (qmake) : Exit Code: 3

```
This is the error when I import to vs. I don't know what happened. If possible, can you provide me a vs demo?

**Comment by VSRonin** [comment]
Looks just like a problem of the tool that you use to import the .pro file. Generate the vs project either manually or via CMake and it will work
