### ISSUE TITLE
计算公式CELL读取问题

### ISSUE THREAD

**Issue by song-kang** [VSRonin/QtXlsxWriter#47]
使用此最新库，读取xlsx文件中的计算公式，读出的并非数值，而是类似“=SUM(O3:V3)”，类似这样的字符串，但excel展示的是某计算后的数值。请问库完成计算公式功能了吗？还是存在此BUG？

**Comment by jslyxyc** [comment]
QXlsx::Document::cellAt(mycell)->value()
或者看下Worksheet::isFormulasVisible() http://qtxlsx.debao.me/worksheet.html#isFormulasVisible

**Comment by VSRonin** [comment]
The library doesn't and never will have a calculation engine. if the value was calculated by another program (e.g. excell) and saved then you can read the saved value
