### ISSUE TITLE
Cannot save .xlsm file.

### ISSUE THREAD

**Issue by gojin78** [VSRonin/QtXlsxWriter#50]
I can read from .xlsm file as good as from .xlsx, but when I write some data in my .xlsm and save it, it breaks and i can't open it. Can I rewrite/make .xlms file with your library?

**Comment by VSRonin** [comment]
Macros do not use a public standard but a Microsoft-propietary format so they can't be managed atm.
This library will not "edit" files but rather re-write them from scratch so any feature that is not supported by the library will be lost in the save
